lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: 'kafka.server<type=BrokerTopicMetrics, name=(.*), topic=(.*)><>Count'
    name: kafka_server_brokertopicmetrics_$1
    labels:
      topic: "$2"
  - pattern: 'kafka.server<type=BrokerTopicMetrics, name=(.*)><>Count'
    name: kafka_server_brokertopicmetrics_$1
  - pattern: 'kafka.consumer<type=consumer-coordinator-metrics, client-id=(.*)><>(.*)'
    name: kafka_consumer_$2
    labels:
      client_id: "$1"
  - pattern: 'kafka.consumer<type=consumer-fetch-manager-metrics, client-id=(.*)><>(.*)'
    name: kafka_consumer_fetch_$2
    labels:
      client_id: "$1"